version: '3.6'

services:
  server:
    build: ../Part03/
    volumes:
      - ${PWD}/../Part03/nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: server
  web:
    image: nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    container_name: proxy
    depends_on:
      - server
